*&---------------------------------------------------------------------*
*&  Include           ZEDR19_PRACTICE009_TOP
*&---------------------------------------------------------------------*

TABLES: ZEDT19_102,
        ZEDT19_103,
        ZEDT19_104,
        ZEDT19_105,
        ZEDT19_106.

DATA : ls_105 TYPE ZEDT19_105,
       lv_db_amt TYPE p DECIMALS 2,
       lv_mon_i TYPE i.

" 사원정보 출력용 구조체
TYPES: BEGIN OF TY_EMP_INFO,
         ICON      TYPE CHAR4,
         ZPERNR    TYPE ZEDT19_102-ZPERNR,    "사원번호
         ZPNAME    TYPE ZEDT19_103-ZPNAME,    "사원이름
         ZDEPCODE  TYPE ZEDT19_102-ZDEPCODE,  "부서코드
         ZDEPNAME  TYPE CHAR20,               "부서명
         ZDEPRANK  TYPE ZEDT19_102-ZDEPRANK,  "직급코드
         ZRANKNAME TYPE CHAR20,               "직급명
         ZEDATE    TYPE ZEDT19_102-ZEDATE,    "입사일
         ZQDATE    TYPE ZEDT19_102-ZQDATE,    "퇴사일
         ZQFLAG    TYPE ZEDT19_102-ZQFLAG,    "퇴사상태(재직/퇴직)
         ZQFLAG_T  TYPE CHAR4,              "퇴사상태(한글)
         ZGENDER   TYPE CHAR4,   "성별(한글)
         ZADDRESS  TYPE ZEDT19_103-ZADDRESS,   "주소
         ZBANKCODE TYPE ZEDT19_106-ZBANKCODE, "은행코드
         ZBANKNAME TYPE CHAR20,               "은행명
         ZACCOUNT TYPE ZEDT19_106-ZACCOUNT,   "계좌번호
         ZYEAR TYPE CHAR4, "년도
         ZRANK TYPE ZEDT19_104-ZRANK, "평가등급
         ZSALARY  TYPE ZEDT19_106-ZSALARY, "계약금액

         ZDATE_D TYPE CHAR10,
         ZQDATE_D TYPE CHAR10,
         ZQDATE_T  TYPE CHAR10,

         WAERS TYPE WAERS, "통화키
       END OF TY_EMP_INFO.

*ALV 출력용 Internal Tables
DATA: GT_EMP_INFO TYPE TABLE OF TY_EMP_INFO,  "사원정보 출력용
      GS_EMP_INFO TYPE TY_EMP_INFO.

* CONSTANTS 선언
CONSTANTS: C_X           TYPE C VALUE 'X',
           C_MALE        TYPE C VALUE 'M',           "남성
           C_FEMALE      TYPE C VALUE 'F',           "여성
           C_MALE_T      TYPE C VALUE '남자',
           C_FEMALE_T    TYPE C VALUE '여자'.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.
DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
       GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GS_VARIANT TYPE DISVARIANT.

DATA : GS_FIELDCAT TYPE LVC_S_FCAT.
DATA : GT_FIELDCAT1 TYPE LVC_T_FCAT.
DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT.
DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_SORT TYPE LVC_S_SORT.
DATA : GT_SORT1 TYPE LVC_T_SORT.
DATA : GT_SORT2 TYPE LVC_T_SORT.
DATA : GT_SORT3 TYPE LVC_T_SORT.

RANGES: R_DATE   FOR ZEDT19_102-DATAB,        "유효기간 범위
        R_PERNR  FOR ZEDT19_102-ZPERNR,       "사원번호 범위
        R_YEAR   FOR ZEDT19_104-ZYEAR.        "연도 범위
