*&---------------------------------------------------------------------*
*&  Include           ZEDR19_PRACTICE008_TOP
*&---------------------------------------------------------------------*

TABLES : ZEDT19_100, ZEDT19_101.

CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.
CONSTANTS : C_A TYPE CHAR1 VALUE 'A'.
RANGES : R_FG FOR ZEDT19_100-ZSALE_FG.
RANGES : R_ZG FOR ZEDT19_101-ZFLAG.

DATA : BEGIN OF GS_ORDER, "주문내역 데이터
  ZORDNO LIKE ZEDT19_100-ZORDNO, "주문번호
  ZIDCODE LIKE ZEDT19_100-ZIDCODE, "회원ID
  ZMATNR LIKE ZEDT19_100-ZMATNR, "제품코드
  ZMTART LIKE ZEDT19_100-ZMTART, "제품유형
  ZMATNAME LIKE ZEDT19_100-ZMATNAME, "제품명
  ZVOLUM LIKE ZEDT19_100-ZVOLUM, "수량
  VRKME LIKE ZEDT19_100-VRKME, "판매단위
  ZNSAMT LIKE ZEDT19_100-ZNSAMT, "판매금액
  ZSLAMT LIKE ZEDT19_100-ZSLAMT, "매출금액
  ZDCAMT LIKE ZEDT19_100-ZDCAMT, "할인금액
  ZWAERS LIKE ZEDT19_100-ZWAERS, "통화
  ZDC_FG LIKE ZEDT19_100-ZDC_FG, "할인구분
  ZSALE_FG LIKE ZEDT19_100-ZSALE_FG, "매출구분
  ZRET_FG LIKE ZEDT19_100-ZRET_FG, "반품구분
  ZJDATE LIKE ZEDT19_100-ZJDATE, "판매일자
  ZRDATE LIKE ZEDT19_100-ZRDATE, "반품일자
  END OF GS_ORDER.
DATA : GT_ORDER LIKE TABLE OF GS_ORDER.

DATA : BEGIN OF GS_0100, "ALV출력용
  ICON TYPE C LENGTH 4,
  ZORDNO LIKE ZEDT19_100-ZORDNO, "주문번호
  ZIDCODE LIKE ZEDT19_100-ZIDCODE, "회원ID
  ZMATNR LIKE ZEDT19_100-ZMATNR, "제품코드
  ZMATNAME LIKE ZEDT19_100-ZMATNAME, "제품코드명
  ZMAT_NAME TYPE C LENGTH 8, "제품유형명
  ZVOLUM LIKE ZEDT19_100-ZVOLUM, "수량
  VRKME LIKE ZEDT19_100-VRKME, "단위
  ZNSAMT LIKE ZEDT19_100-ZNSAMT, "판매금액
  ZSLAMT LIKE ZEDT19_100-ZSLAMT, "매출금액
  ZDCAMT LIKE ZEDT19_100-ZDCAMT, "할인금액
  ZWAERS LIKE ZEDT19_100-ZWAERS, "통화
  ZSALE_NAME TYPE C LENGTH 4, "매출구분
  ZJDATE LIKE ZEDT19_100-ZJDATE, "판매일자
  ZRET_NAME TYPE C LENGTH 10, "반품구분
  ZRDATE LIKE ZEDT19_100-ZRDATE, "반품일자
  END OF GS_0100.
DATA : GT_0100 LIKE TABLE OF GS_0100.

DATA : BEGIN OF GS_DELIVERY, "배송내역 데이터
  ZORDNO LIKE ZEDT19_101-ZORDNO, "주문번호
  ZIDCODE LIKE ZEDT19_101-ZIDCODE, "회원ID
  ZMATNR LIKE ZEDT19_101-ZMATNR, "제품코드
  ZMTART LIKE ZEDT19_101-ZMTART, "제품유형
  ZMATNAME LIKE ZEDT19_101-ZMATNAME, "제품명
  ZVOLUM LIKE ZEDT19_101-ZVOLUM, "수량
  VRKME LIKE ZEDT19_101-VRKME, "판매단위
  ZSLAMT LIKE ZEDT19_101-ZSLAMT, "매출금액
  ZWAERS LIKE ZEDT19_100-ZWAERS, "통화
  ZDFLAG LIKE ZEDT19_101-ZDFLAG, "배송현황
  ZDGUBUN LIKE ZEDT19_101-ZDGUBUN, "배송지역
  ZDDATE LIKE ZEDT19_101-ZDDATE, "배송일자
  ZRDATE LIKE ZEDT19_101-ZRDATE, "반품일자
  ZFLAG LIKE ZEDT19_101-ZFLAG, "FLAG
  END OF GS_DELIVERY.
DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY.

DATA : BEGIN OF GS_0200, "ALV출력용
  ICON TYPE C LENGTH 4,
  ZORDNO LIKE ZEDT19_101-ZORDNO, "주문번호
  ZIDCODE LIKE ZEDT19_101-ZIDCODE, "회원ID
  ZMATNR LIKE ZEDT19_101-ZMATNR, "제품코드
  ZMATNAME LIKE ZEDT19_101-ZMATNAME, "제품명
  ZMAT_NAME TYPE C LENGTH 8, "제품유형명
  ZVOLUM LIKE ZEDT19_101-ZVOLUM, "수량
  VRKME LIKE ZEDT19_101-VRKME, "판매단위
  ZSLAMT LIKE ZEDT19_101-ZSLAMT, "매출금액
  ZWAERS LIKE ZEDT19_100-ZWAERS, "통화
  ZDFLAG_NAME TYPE C LENGTH 8, "배송현황
  ZDGUBUN_NAME TYPE C LENGTH 6, "배송지역
  ZDDATE LIKE ZEDT19_101-ZDDATE, "배송일자
  ZRDATE LIKE ZEDT19_101-ZRDATE, "반품일자
  ZFLAG LIKE ZEDT19_101-ZFLAG, "FLAG
  END OF GS_0200.
DATA : GT_0200 LIKE TABLE OF GS_0200.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_GRID_100 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID_200 TYPE REF TO CL_GUI_ALV_GRID.

DATA : GS_FIELDCAT TYPE LVC_S_FCAT,
       GT_FIELDCAT TYPE LVC_T_FCAT.
DATA : GS_LAYOUT TYPE LVC_S_LAYO.
DATA : GS_SORT TYPE LVC_S_SORT .
DATA : GT_SORT TYPE LVC_T_SORT.

DATA : GS_VARIANT TYPE DISVARIANT.
